name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1.20.4
        with:
          otp-version: "28.0"
          gleam-version: "1.11"
          rebar3-version: "3"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
      - run: gleam test --target javascript
